version: '3.8'

services:
  test_app:
    build:
      context: .
      dockerfile: zephyr/Dockerfile.test
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - ENV=test
      - TESTING=1
      - DB_SERVER=db
      - DB_USER=zephyr
      - DB_PASSWORD=zephyr
      - DB_NAME=zephyr_test
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
    depends_on:
      - db
      - redis
  db:
    image: library/postgres:12.7
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=zephyr
      - POSTGRES_PASSWORD=zephyr
      - POSTGRES_DB=zephyr_test
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    expose:
      - "6379"
    restart: always
volumes:
  db_data: