version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/app/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DB_SERVER
      - DB_USER
      - DB_PASSWORD
      - DB_NAME