version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: zephyr/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - ENV=dev
      - TESTING=0
      - DB_SERVER
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
    depends_on:
      - redis
  redis:
    image: redis:6.2
    expose:
      - "6379"
    restart: always