# pull official base image
FROM python:3.8.7-slim-buster

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1 \
  POETRY_VERSION=1.1.8

# install system dependencies
RUN apt-get -y update \
  && apt-get -y upgrade \
  && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
RUN pip install pytz
RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# add app
COPY . .

CMD ["sh", "./zephyr/run_test.sh"]